apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-operator-tests
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "tekton.dev"
  resources:
  - pipelineruns
  - pipelines
  - taskruns
  - tasks
  verbs:
  - get
  - create
  - list
  - delete
