apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-operator-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-operator-tests
subjects:
- kind: ServiceAccount
  name: tekton-operator-tests
  namespace: default
